FROM node:22-alpine

ENV NODE_ENV=development

ENV PORT=3000


WORKDIR /workspace
COPY tsconfig.base.json ./
COPY common/ /workspace/common/
COPY common-libs/ /workspace/common-libs/
RUN npm init -y && npm install nodemailer @types/nodemailer
WORKDIR /workspace/user-service

COPY user-service/package*.json ./

RUN npm install 

RUN npm install -g typescript ts-node

COPY user-service/tsconfig.json ./
COPY user-service/ ./


EXPOSE 3000




CMD [ "npm", "run", "start:dev" ]