FROM node:22-alpine

ENV NODE_ENV=development

ENV PORT=3001


WORKDIR /workspace
COPY tsconfig.base.json ./
COPY common/ /workspace/common/
COPY common-libs/ /workspace/common-libs/
RUN npm init -y && npm install nodemailer @types/nodemailer

WORKDIR /workspace/messaging-service

COPY messaging-service/package*.json ./

RUN npm install

RUN npm install -g typescript ts-node

# Copy the base config to parent directory inside container
COPY messaging-service/tsconfig.json ./
COPY messaging-service/ ./

EXPOSE 3001

CMD [ "npm", "run", "start:dev" ]